name: MLOps Automation

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly (Feature Pipeline)
    - cron: "0 0 * * 0"  # Runs weekly (Model Training)

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Feature Pipeline (Hourly)
        if: github.event.schedule == 'cron' && github.event.schedule == '0 * * * *'
        run: python scripts/fetch_aqi.py && python scripts/store_features.py

      - name: Run Training Pipeline (Weekly)
        if: github.event.schedule == 'cron' && github.event.schedule == '0 0 * * 0'
        run: python scripts/train_model.py
